# Generated by Django 6.0.6 on 2026-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
