# Generated by Django 6.0.6 on 2026-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_yacht_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoraircraft',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
