# Generated by Django 6.0.6 on 2026-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_operatoraircraft_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatoryacht',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
