# Generated by Django 6.0.6 on 2026-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_operatoryacht_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqbid',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='submitted', max_length=12),
        ),
    ]
