# Generated by Django 6.0.6 on 2026-07-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rfqbid_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rfqbid',
            unique_together=set(),
        ),
    ]
